### ISSUE TITLE
Determine if currently opened workspace contains a Quarkus project

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#71] opened 2019-09-12 14:14 UTC
### Case 1
For the wizard that helps add Quarkus extensions (launched with the "Quarkus: Add extensions to current project" command), the wizard tries to add Quarkus extensions even if the currently opened project is not a Quarkus project. It only checks if a pom.xml file exists under the currently opened workspace folder(s).

### Case 2
In addition, when calling the "Quarkus: Debug current Quarkus project" VS Code command, it only checks if a pom.xml file exists under the current workspace folder.

In both cases, the code does not confirm that the pom.xml is a part of a Quarkus project. It would be great if it did, so that an error message like "Current maven project is not a Quarkus project" could appear in these cases.

**Comment by angelozerr** [comment] 2019-10-14 04:40
Perhaps quarkus ls should provide this method isQuarkusProject and vscode-quarkus client will consume this new ls service?

**Comment by fbricon** [comment] 2020-01-24 09:16
Closing as duplicate of #45

**Closed as completed by fbricon** 2020-01-24 09:16 UTC
Labels: duplicate
