### ISSUE TITLE
Quarkus welcome page shown on every activation of extension

### ISSUE THREAD

**Issue by rgrunber** [redhat-developer/vscode-quarkus#328] opened 2021-01-18 15:39 UTC
The Quarkus welcome page is automatically shown on activation of the quarkus extension if `quarkus.tools.alwaysShowWelcomePage` has not been set to false. Even though it can be toggled from the bottom of the welcome page, perhaps this isn't very visible. Should we move it up, or maybe just display the welcome page one time.

The justification for the welcome page behaviour was likely : https://github.com/redhat-developer/vscode-quarkus/pull/91#issuecomment-538439085 .

**Comment by deboer-tim** [comment] 2021-01-18 23:21
I'll admit to being the cause of this issue - I had gotten into the behaviour of closing the tab every time I started VS Code, each time wondering if the extension had been updated and never reading through the text. It's the only extension I have installed that does this, and it was popping up for clearly unrelated Java code (due to the way VS Code works).

I'm not sure if I would have eventually gotten more frustrated or taken the time to read the text. Moving the checkbox to the top would have helped with noticing it. Personally I'd prefer changing the behaviour to not open on every start by default, but it's probably not worth changing unless others are also getting annoyed.

**Comment by rgrunber** [comment] 2021-01-19 18:17
I'm fine with keeping this open as even in Eclipse, the welcome page is only shown once per activation in new workspace.

I suspect we can use [ExtensionContext.workspaceState](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage) to avoid showing the welcome page after the first time displaying, per workspace.

**Closed as completed** 2021-03-04 19:30 UTC
