### ISSUE TITLE
Add support for MicroProfile REST properties

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/vscode-quarkus#104] opened 2019-10-10 08:18 UTC
When using Rest client you need to configure the location of the REST service (ie com.example.BeerGateway/mp-rest/url) The problem is that when you set it there is always a warning message telling you that this property is not used (see screenshot)
![Screenshot 2019-10-10 at 10 09 24](https://user-images.githubusercontent.com/1517153/66551003-daa51200-eb46-11e9-95a5-b98dcff76df8.png)

I think that the warning should disappear if there is a class in the workspace identified by the property (in the previous case `com.example.BeerGateway`)

**Comment by fbricon** [comment] 2019-10-10 08:23
@lordofthejars can you please provide a sample project reproducing this issue?

**Comment by lordofthejars** [comment] 2019-10-10 08:25
https://github.com/lordofthejars/quarkus-https

**Comment by fbricon** [comment] 2019-10-10 08:29
as a workaround you can silence the warning with:
```json
 "quarkus.tools.validation.unknown.excluded": [
        "com.example.BeerGateway/mp-rest/url"
    ]
```

**Comment by angelozerr** [comment] 2019-10-10 08:55
@lordofthejars thanks for having shared your project.

> I think that the warning should disappear if there is a class in the workspace identified by the property

If I understand your sample. You have an interface [com.example.BeerGateway](https://github.com/lordofthejars/quarkus-https/blob/master/src/main/java/com/example/BeerGateway.java) bounded with `@RegisterRestClient` annotation:

```java
package com.example;
...
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

@Path("/v2")
@RegisterRestClient
public interface BeerGateway {

    @GET
    @Path("/beers")
    @Produces(MediaType.APPLICATION_JSON)
    CompletionStage<List<Beer>> getBeers(@QueryParam("page") int page);
}
```

Using `@RegisterRestClient` annotation gives you the capability to customize the url:

`com.example.BeerGateway/mp-rest/url=https://api.punkapi.com`

So if you wish manage this case correctly we should:

 * manage completion, validation, hover, definition for interface bound with `@RegisterRestClient`.

Ex: completion for:

`com.exam | `

should provide this completion item

`com.example.BeerGateway/mp-rest/url=`

because BeerGateway is bound with `@RegisterRestClient` and validation should ignore warning for `com.example.BeerGateway/mp-rest/url` but add a warning for `com.example.BeerGateway/mp-rest/XXXXXXXXXX`

@fbricon what do you think about this ideal idea? Do we should take care of  `@RegisterRestClient` annotation?

@lordofthejars today we collect Quarkus properties from ConfigProperty and ConfigRoot annotation. It seems that there are another cases like  `@RegisterRestClient`. 

Have you some ideas if there are some annotations that we should take care of?

**Comment by lordofthejars** [comment] 2019-10-10 09:21
Yeah there are more in Rest Client: 
* https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/ssl.asciidoc
* https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/cdi.asciidoc#support-for-microprofile-config

Fault tolerance:
* https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/configuration.asciidoc

**Comment by angelozerr** [comment] 2019-10-10 09:38
Thank @lordofthejars for your feedback. And it seems that there are other `microprofile` project https://github.com/eclipse?utf8=%E2%9C%93&q=microprofile&type=&language=

The question is should manage all annotations? Most important annotations? Ignore warning at the hand as @fbricon suggested?

**Comment by jclingan** [comment] 2019-11-24 20:16
Update: DUPLICATE comment. I missed a previous comment that included fault tolerance.
I'd like to extend this issue with support for MicroProfile Fault Tolerance configuration annotation parameter support. See [spec doc "Fault Tolerance Configuration" section](https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/configuration.asciidoc). Both MicroProfile Rest Client and Fault tolerance support the same general pattern: [class-name]/some-spec-related-path-notation.

**Comment by angelozerr** [comment] 2019-11-25 12:51
@jclingan thanks for your feedback, we would like to work on this issue but we must do that step by step because it's a long and hard issue to manage correctly microprofile property.

Take a sample with :

`com.example.BeerGateway/mp-rest/url=https://api.punkapi.com`

We need to : 

 * manage completion for class name (like BeerGateway)
 * manage completion for mp-rest/url, mp-rest/uri, etc after class name
 * manage validation for class name (like BeerGateway) 
 * manage validation for /mp-rest/url, /mp-rest/uri, etc after class name
 * manage definition for class name (ex: Ctrl=Click on BeerGateway should open the Java file)
 * manage hover
 * manage references from Java file.

As you see there are a lot of features that we could implement, but we would like to know which features is important for you and which mircroprofile features (which microprofile annotation) that we should implement it (Fault Toerance Configuration, RegisterRestClient, etc?) .

It should be very cool if you could give us a detailed list (completion, validation, etc for  fault tolerance, rest client, etc) of features that you want to have and tell us if it's important or not.

Many thanks!

**Comment by angelozerr** [comment] 2019-12-12 14:00
@lordofthejars @jclingan I'm working on this issue to support MicroProfile REST client properties, here a demo:

![MPRestDemo](https://user-images.githubusercontent.com/1932211/70718228-1b104000-1cf0-11ea-92a5-dcec494118f4.gif)

**Comment by jclingan** [comment] 2019-12-14 01:38
Nice! I look forward to using it.

**Comment by angelozerr** [comment] 2019-12-16 18:59
Fixed with https://github.com/redhat-developer/quarkus-ls/pull/163 (for mp-rest).

For fault tolerance, I open a new issue at https://github.com/redhat-developer/vscode-quarkus/issues/174

**Closed as completed by angelozerr** 2019-12-16 18:59 UTC
Labels: enhancement
