### ISSUE TITLE
[Qute] Add language configuration for Qute syntax

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#183] opened 2020-01-03 13:47 UTC
Add a language configuration for Qute to manages matching bracket, comments etc like I had done with Freemarker in https://github.com/angelozerr/lsp4e-freemarker/blob/master/org.eclipse.lsp4e.freemarker/language-configurations/language-configuration.json

This language configuration could be used in Eclipse IDE too with TM4E  /cc @jeffmaury

**Comment by fbricon** [comment] 2020-01-10 15:09
closing as duplicate of #182

**Closed as completed by fbricon** 2020-01-10 15:09 UTC
Labels: duplicate, qute
